name: Deploy React to EC2 (Nginx)

on:
  push:
    branches: [ "main" ]

# Hủy run cũ nếu có commit mới vào main
concurrency:
  group: "deploy-main"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      # Giảm mức RAM Node dùng, tránh OOM trên máy 1GB
      NODE_OPTIONS: "--max-old-space-size=512"
      # Tránh cảnh báo làm fail build trên CRA
      CI: "false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps (lean)
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy to Nginx
        run: |
          sudo rsync -a --delete ./build/ /var/www/reactapp/
          sudo chown -R nginx:nginx /var/www/reactapp
          sudo chmod -R 755 /var/www/reactapp
          sudo nginx -t
          sudo systemctl reload nginx
