name: Build on GitHub, Deploy to EC2

on:
  push:
    branches: [ "main" ]

concurrency:
  group: "deploy-main"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          CI: "false"
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy files to EC2
        run: |
          rsync -az --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/deploy_build/

      - name: Publish on Nginx
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo rsync -a --delete /home/${{ secrets.EC2_USER }}/deploy_build/ ${EC2_PATH:-/var/www/reactapp}/ \
             && sudo chown -R nginx:nginx ${EC2_PATH:-/var/www/reactapp} \
             && sudo chmod -R 755 ${EC2_PATH:-/var/www/reactapp} \
             && sudo nginx -t && sudo systemctl reload nginx"
        env:
          EC2_PATH: ${{ secrets.EC2_PATH }}
